include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - '**.gen.dart'
    - '**.freezed.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
