name: stacktrace_parser
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.4
  dartx: ^1.1.0
  deep_pick: ^0.10.0
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  gap: ^2.0.0
  go_router: ^4.2.7
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
