name: stacktrace_parser
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.4.4
  convert: ^3.0.2
  cryptography: ^2.0.5
  dartx: ^1.1.0
  
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  go_router: ^4.2.7
  json_annotation: ^4.6.0
  
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lint: ^1.10.0

flutter:
  uses-material-design: true
