name: stacktrace_parser
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dartx: ^1.1.0
  flutter:
    sdk: flutter
  gap: ^2.0.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
